@echo off
echo Starting EURIA Food Backend Server...
cd /d "c:\Users\YANN\Desktop\Emergent-app\backend"
echo Activating virtual environment...
call "C:/Users/YANN/Desktop/Emergent-app/.venv/Scripts/activate.bat"
echo Starting server on port 8001...
python server.py
pause
